package com.BankingSystem.entity.notification;

public enum InAppNotificationType {
    LOAN_APPLICATION_RECEIVED,
    CREDIT_CARD_APPLICATION_RECEIVED,
    BRANCH_TRANSFER_CURRENT_BRANCH,
    BRANCH_TRANSFER_NEW_BRANCH,
    MANAGER_ASSIGNED,
    MANAGER_REVOKED,
    MANAGER_TRANSFERRED,
    BRANCH_CREATED,
    BRANCH_DEACTIVATED,
    SYSTEM_ALERT
}
